export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAIL = "MAKE_ORDER_FAIL";

export const FETCH_RECEIPTS_SUCCESS = "FETCH_RECEIPTS_SUCCESS"; 
export const FETCH_RECEIPTS_FAIL = "FETCH_RECEIPTS_FAIL";

export const FETCH_RECEIPT_SUCCESS = "FETCH_RECEIPT_SUCCESS";
export const FETCH_RECEIPT_FAIL = "FETCH_RECEIPT_FAIL";
